### ISSUE TITLE
Text file considered as binary

### ISSUE THREAD

**Issue by mhagnumdw** [ec4j/editorconfig-maven-plugin#23]
The attached text file is considered as binary, resulting in build failure. If you remove the accented characters the problem will disappear.

[simplelogger.properties.zip](https://github.com/ec4j/editorconfig-maven-plugin/files/1968309/simplelogger.properties.zip)

Command
`mvn org.ec4j.maven:editorconfig-maven-plugin:check -Deditorconfig.excludes="db/**,log/**"`

Maven output
```
[ERROR] Failed to execute goal org.ec4j.maven:editorconfig-maven-plugin:0.0.5:check (default-cli) on project xyz: 
[ERROR] 
[ERROR] Could not read /home/user/ambiente/workspace/xyz/src/main/resources/simplelogger.properties. This may mean that it is a binary file and you should exclude it from editorconfig processing.
[ERROR] 
[ERROR] : Input length = 1
[ERROR] -> [Help 1]
```
Maven output with relevant stacktrace
```
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read(BufferedReader.java:182)
	at org.ec4j.maven.lint.api.LineReader$DelegatingLineReader.read(LineReader.java:66)
	at org.ec4j.maven.lint.api.LineReader$DelegatingLineReader.readLine(LineReader.java:124)
	at org.ec4j.maven.linters.TextLinter.process(TextLinter.java:156)
	... 23 more
```

**Comment by ppalaga** [comment]
Thanks for the report. Clearly, there is a mismatch between the encoding of the file and the encoding the plugin is using. Could you please provide the following info to be able to tell if this is a bug or just a misconfiguration?

(1) What is the encoding of the file? 

(2) Have you set the encoding at the Maven level for all files, via `editorconfig.encoding` or `project.build.sourceEncoding` property?

(3) Have you set `charset` in any of the relevant `.editorconfig` files?

**Comment by ppalaga** [comment]
Thanks, let me try to reproduce it.
