### ISSUE TITLE
Failure to run with Maven due to slf4j stuff

### ISSUE THREAD

**Issue by ashleyscopes** [ec4j/editorconfig-maven-plugin#33]
Tried running on a project using `mvn editorconfig:check`.

Unfortunately, it is failing with 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.190 s
[INFO] Finished at: 2018-12-07T09:51:06+00:00
[INFO] Final Memory: 13M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.ec4j.maven:editorconfig-maven-plugin:0.0.7:check (default-cli) on project xxxxxx: Execution default-cli of goal org.ec4j.maven:editorconfig-maven-plugin:0.0.7:check failed: Could not find org.ec4j.maven.lint.api.Logger$LogLevel for org.slf4j.Logger [org.slf4j.impl.SimpleLogger(org.ec4j.maven.lint.api.LinterRegistry)] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.ec4j.maven:editorconfig-maven-plugin:0.0.7:check (default-cli) on project xxxxxx: Execution default-cli of goal org.ec4j.maven:editorconfig-maven-plugin:0.0.7:check failed: Could not find org.ec4j.maven.lint.api.Logger$LogLevel for org.slf4j.Logger [org.slf4j.impl.SimpleLogger(org.ec4j.maven.lint.api.LinterRegistry)]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.ec4j.maven:editorconfig-maven-plugin:0.0.7:check failed: Could not find org.ec4j.maven.lint.api.Logger$LogLevel for org.slf4j.Logger [org.slf4j.impl.SimpleLogger(org.ec4j.maven.lint.api.LinterRegistry)]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalStateException: Could not find org.ec4j.maven.lint.api.Logger$LogLevel for org.slf4j.Logger [org.slf4j.impl.SimpleLogger(org.ec4j.maven.lint.api.LinterRegistry)]
        at org.ec4j.maven.Slf4jLintLogger.toEc4jLogLevel(Slf4jLintLogger.java:39)
        at org.ec4j.maven.Slf4jLintLogger.<init>(Slf4jLintLogger.java:47)
        at org.ec4j.maven.AbstractEditorconfigMojo.buildLinterRegistry(AbstractEditorconfigMojo.java:165)
        at org.ec4j.maven.AbstractEditorconfigMojo.execute(AbstractEditorconfigMojo.java:219)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by ashleyscopes** [comment]
0.0.7 as on the project documentation.

Didn't notice 0.0.8 existed; so will check that now.

**Comment by ashleyscopes** [comment]
Yep 0.0.8 is fixed. Might it be worth updating that documentation to reflect on the new version?

Thanks for the quick reply though, greatly appreciated 👍

**Comment by ppalaga** [comment]
> 0.0.7 as on the project documentation

Which page is that?

**Comment by ashleyscopes** [comment]
Cheers :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
